FROM nginx:alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy configs
COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d/ /etc/nginx/conf.d/

# Copy certs
COPY certs/ /etc/nginx/certs/

# Copy frontend build
COPY ../frontend/web/build /usr/share/nginx/html

# Healthcheck
HEALTHCHECK CMD wget --quiet --tries=1 --spider http://localhost/health || exit 1

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]