# Generated by Django 5.1 on 2026-04-20 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('online_status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('dnd', 'Do Not Disturb'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('fcm_token', models.TextField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', null=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
