server {
    listen 80;

    location /health {
        return 200 "OK";
    }

    # Redirect HTTP → HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    include /etc/nginx/conf.d/security.conf;
    include /etc/nginx/conf.d/rate-limit.conf;
    include /etc/nginx/conf.d/cors.conf;

    # Authentication
    auth_request /auth;

    # USERS
    location /api/users/ {
        proxy_pass http://user_service;
        include proxy_params;
    }

    # WORKSPACE
    location /api/workspaces/ {
        proxy_pass http://workspace_service;
        include proxy_params;
    }

    # CHAT
    location /api/chat/ {
        proxy_pass http://chat_service;
        include proxy_params;
    }

    # DOCS
    location /api/docs/ {
        proxy_pass http://collaboration_service;
        include proxy_params;
    }

    # NOTIFICATIONS
    location /api/notifications/ {
        proxy_pass http://notification_service;
        include proxy_params;
    }

    # MEDIA
    location /api/media/ {
        proxy_pass http://media_service;
        include proxy_params;
    }

    # Auth validation endpoint
    location = /auth {
        proxy_pass http://auth_service/api/auth/validate/;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }

    include /etc/nginx/conf.d/websocket.conf;
    include /etc/nginx/conf.d/frontend.conf;
}