add_header X-Frame-Options SAMEORIGIN;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";

# Basic auth header pass-through
proxy_set_header Authorization $http_authorization;