upstream user_service {
    server user-service:8000;
}

upstream chat_service {
    least_conn;
    server chat-service-1:8000;
    server chat-service-2:8000;
}

upstream collaboration_service {
    least_conn;
    server collaboration-service:8000;
}

upstream notification_service {
    server notification-service:8000;
}

upstream media_service {
    server media-service:8000;
}

upstream workspace_service {
    server workspace-service:8000;
}

upstream auth_service {
    server user-service:8000;
}