# CHAT WS
location /ws/chat/ {
    proxy_pass http://chat_service;
    include proxy_ws;
}

# COLLAB WS
location /ws/docs/ {
    proxy_pass http://collaboration_service;
    include proxy_ws;
}

# NOTIFICATIONS WS
location /ws/notifications/ {
    proxy_pass http://notification_service;
    include proxy_ws;
}

# MEDIA WS (WebRTC signaling)
location /ws/media/ {
    proxy_pass http://media_service;
    include proxy_ws;
}