# Generated by Django 5.1 on 2026-04-20 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IceServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='e.g. turn:coturn.example.com:3478', max_length=255)),
                ('server_type', models.CharField(choices=[('stun', 'STUN'), ('turn', 'TURN')], default='stun', max_length=10)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('credential', models.CharField(blank=True, max_length=255, null=True)),
                ('hmac_secret', models.CharField(blank=True, help_text='coturn static-auth-secret for time-limited HMAC credentials', max_length=255, null=True)),
                ('credential_ttl', models.PositiveIntegerField(default=86400, help_text='TURN credential TTL in seconds (default 24h)')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher = preferred')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('room_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('screen', 'Screen Share')], default='video', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Prevent new joins when True')),
                ('max_participants', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='Bytes', null=True)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='app.room')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-host'), ('participant', 'Participant')], default='participant', max_length=20)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_video_on', models.BooleanField(default=True)),
                ('is_screen_sharing', models.BooleanField(default=False)),
                ('connection_id', models.CharField(blank=True, max_length=255, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app.room')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_user_id', models.UUIDField(db_index=True)),
                ('signal_type', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('ice_candidate', 'ICE Candidate')], max_length=20)),
                ('signal_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(db_index=True, default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='app.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordingChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('file_url', models.URLField()),
                ('size', models.PositiveBigIntegerField(help_text='Bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='app.recording')),
            ],
            options={
                'ordering': ['chunk_index'],
                'unique_together': {('recording', 'chunk_index')},
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['workspace_id'], name='app_room_workspa_a85ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active'], name='app_room_is_acti_d5e2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['room'], name='app_recordi_room_id_ff42a1_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room'], name='app_partici_room_id_c6ae71_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user'], name='app_partici_user_id_cb959d_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room', 'left_at'], name='app_partici_room_id_598ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['room'], name='app_signal_room_id_25536c_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['target_user_id', 'is_delivered'], name='app_signal_target__c3731d_idx'),
        ),
    ]
