# Generated by Django 5.1 on 2026-04-22 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_room_roomparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_participants',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='is_screen_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('participant_count', models.IntegerField(default=0)),
                ('recording_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_history', to='app.room')),
            ],
            options={
                'verbose_name_plural': 'Call histories',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('call_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.callhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
    ]
